/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pdm.view;

import java.util.ArrayList;
import pdm.Controller.ClienteController;
import pdm.Controller.FornecedorController;
import pdm.Controller.ProdutoController;
import pdm.Model.Cliente;
import pdm.Model.Fornecedor;
import pdm.Model.Produto;

/**
 *
 * @author Uso Exclusivo
 */
public class JFramePDM extends javax.swing.JFrame {
    
    private ArrayList<Cliente> clientes = new ArrayList<>();
    private ArrayList<Produto> produtos = new ArrayList<>();
    private ArrayList<Fornecedor> fornecedores = new ArrayList<>();
    private int produtoAtual = -1;
    private int clienteAtual = -1;
    private int fornecedorAtual = -1;
    
    private ClienteController clControl = new ClienteController();
    private ProdutoController prControl = new ProdutoController();
    private FornecedorController frControl = new FornecedorController();
    
    

    /**
     * Creates new form NewJFrame
     */
    public JFramePDM() {
        initComponents();
        prepareComponents();
        buscarProdutosByCriteria("");
        buscarClientesByCriteria("");
        buscarFornecedoresByCriteria("");

        /* PRODUTOS */
        prodNotEditable();

        /* CLIENTES */
        cliNotEditable();

        /* FORNECEDORES */
        forNotEditable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pInicio = new javax.swing.JPanel();
        pProdutos = new javax.swing.JPanel();
        tfFornecedor = new javax.swing.JTextField();
        btAnterior = new javax.swing.JButton();
        btProximo = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        lbValorQtd = new javax.swing.JLabel();
        lbTamanho = new javax.swing.JLabel();
        lbValorAtual = new javax.swing.JLabel();
        tfPrecoVenda = new javax.swing.JTextField();
        tfPrecoCompra = new javax.swing.JTextField();
        tfDescricao = new javax.swing.JTextField();
        tfNome = new javax.swing.JTextField();
        tfCodigo = new javax.swing.JTextField();
        tfTamanho = new javax.swing.JTextField();
        tfbuscar = new javax.swing.JTextField();
        lbFornecedor = new javax.swing.JLabel();
        lbPrecoVenda = new javax.swing.JLabel();
        lbPrecoCompra = new javax.swing.JLabel();
        lbDescricao = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        lbCodigo = new javax.swing.JLabel();
        lbQtd = new javax.swing.JLabel();
        btEditar = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();
        btBuscar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btCancelar = new javax.swing.JButton();
        pClientes = new javax.swing.JPanel();
        tfbuscar1 = new javax.swing.JTextField();
        btBuscar1 = new javax.swing.JButton();
        btAnterior1 = new javax.swing.JButton();
        lbValorAtual1 = new javax.swing.JLabel();
        btProximo1 = new javax.swing.JButton();
        tfCodigo1 = new javax.swing.JTextField();
        tfNome1 = new javax.swing.JTextField();
        tfDescricao1 = new javax.swing.JTextField();
        tfMediaCompras = new javax.swing.JTextField();
        tfFrequencia = new javax.swing.JTextField();
        lbPrecoVenda1 = new javax.swing.JLabel();
        lbPrecoCompra1 = new javax.swing.JLabel();
        lbDescricao1 = new javax.swing.JLabel();
        lbNome1 = new javax.swing.JLabel();
        lbCodigo1 = new javax.swing.JLabel();
        btNovo1 = new javax.swing.JButton();
        btSalvar1 = new javax.swing.JButton();
        btEditar1 = new javax.swing.JButton();
        btExcluir1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        tfCidade1 = new javax.swing.JTextField();
        lbTamanho4 = new javax.swing.JLabel();
        lbTamanho5 = new javax.swing.JLabel();
        tfUf1 = new javax.swing.JTextField();
        tfTelefone1 = new javax.swing.JTextField();
        lbPrecoCompra3 = new javax.swing.JLabel();
        lbQtd4 = new javax.swing.JLabel();
        lbValorQtd4 = new javax.swing.JLabel();
        btCancelar3 = new javax.swing.JButton();
        pFornecedores = new javax.swing.JPanel();
        tfbuscar2 = new javax.swing.JTextField();
        btBuscar2 = new javax.swing.JButton();
        btAnterior2 = new javax.swing.JButton();
        lbValorAtual2 = new javax.swing.JLabel();
        btProximo2 = new javax.swing.JButton();
        tfCodigo2 = new javax.swing.JTextField();
        tfNome2 = new javax.swing.JTextField();
        tfDescricao2 = new javax.swing.JTextField();
        tfTelefone = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        tfEndereco = new javax.swing.JTextField();
        tfCidade = new javax.swing.JTextField();
        lbTamanho2 = new javax.swing.JLabel();
        lbFornecedor2 = new javax.swing.JLabel();
        lbPrecoVenda2 = new javax.swing.JLabel();
        lbPrecoCompra2 = new javax.swing.JLabel();
        lbDescricao2 = new javax.swing.JLabel();
        lbNome2 = new javax.swing.JLabel();
        lbCodigo2 = new javax.swing.JLabel();
        btSalvar2 = new javax.swing.JButton();
        btEditar2 = new javax.swing.JButton();
        btExcluir2 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        tfUf = new javax.swing.JTextField();
        lbTamanho3 = new javax.swing.JLabel();
        lbQtd3 = new javax.swing.JLabel();
        lbValorQtd3 = new javax.swing.JLabel();
        btNovo3 = new javax.swing.JButton();
        btCancelar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PDM");
        setMinimumSize(new java.awt.Dimension(640, 520));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(656, 558));
        jPanel1.setMinimumSize(new java.awt.Dimension(640, 480));
        jPanel1.setName("panelFrame"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(656, 558));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setMaximumSize(new java.awt.Dimension(640, 480));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(640, 480));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(656, 558));

        pInicio.setMaximumSize(new java.awt.Dimension(640, 520));
        pInicio.setMinimumSize(new java.awt.Dimension(640, 520));
        pInicio.setPreferredSize(new java.awt.Dimension(656, 558));

        javax.swing.GroupLayout pInicioLayout = new javax.swing.GroupLayout(pInicio);
        pInicio.setLayout(pInicioLayout);
        pInicioLayout.setHorizontalGroup(
            pInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 651, Short.MAX_VALUE)
        );
        pInicioLayout.setVerticalGroup(
            pInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Inicio", pInicio);
        pInicio.getAccessibleContext().setAccessibleName("");

        pProdutos.setMaximumSize(new java.awt.Dimension(656, 558));
        pProdutos.setMinimumSize(new java.awt.Dimension(640, 520));
        pProdutos.setPreferredSize(new java.awt.Dimension(656, 558));
        pProdutos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfFornecedor.setPreferredSize(new java.awt.Dimension(6, 21));
        pProdutos.add(tfFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 230, 30));

        btAnterior.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btAnterior.setText("<<");
        btAnterior.setToolTipText("Anterior");
        btAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnteriorActionPerformed(evt);
            }
        });
        pProdutos.add(btAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 50, 30));

        btProximo.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btProximo.setText(">>");
        btProximo.setToolTipText("Próximo");
        btProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProximoActionPerformed(evt);
            }
        });
        pProdutos.add(btProximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 50, 30));

        btExcluir.setBackground(new java.awt.Color(255, 51, 51));
        btExcluir.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        pProdutos.add(btExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, 70, 30));

        lbValorQtd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbValorQtd.setText("1");
        lbValorQtd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pProdutos.add(lbValorQtd, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 60, 30));

        lbTamanho.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTamanho.setText("Tamanho:");
        pProdutos.add(lbTamanho, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 60, 30));

        lbValorAtual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbValorAtual.setText("1");
        lbValorAtual.setToolTipText("");
        lbValorAtual.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pProdutos.add(lbValorAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 30, 30));

        tfPrecoVenda.setPreferredSize(new java.awt.Dimension(6, 21));
        pProdutos.add(tfPrecoVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 230, 30));

        tfPrecoCompra.setPreferredSize(new java.awt.Dimension(6, 21));
        pProdutos.add(tfPrecoCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 230, 30));

        tfDescricao.setPreferredSize(new java.awt.Dimension(6, 21));
        pProdutos.add(tfDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 230, 30));

        tfNome.setPreferredSize(new java.awt.Dimension(6, 21));
        pProdutos.add(tfNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 230, 30));

        tfCodigo.setPreferredSize(new java.awt.Dimension(6, 21));
        pProdutos.add(tfCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 150, 30));

        tfTamanho.setPreferredSize(new java.awt.Dimension(6, 21));
        pProdutos.add(tfTamanho, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 230, 30));

        tfbuscar.setPreferredSize(new java.awt.Dimension(6, 21));
        pProdutos.add(tfbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 180, 30));

        lbFornecedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFornecedor.setText("Fornecedor:");
        pProdutos.add(lbFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 70, 30));

        lbPrecoVenda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPrecoVenda.setText("Preço Venda:");
        pProdutos.add(lbPrecoVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 90, 30));

        lbPrecoCompra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPrecoCompra.setText("Preço Compra:");
        pProdutos.add(lbPrecoCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 110, 30));

        lbDescricao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDescricao.setText("Descrição:");
        pProdutos.add(lbDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 60, 30));

        lbNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNome.setText("Nome:");
        pProdutos.add(lbNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 50, 30));

        lbCodigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCodigo.setText("Código:");
        pProdutos.add(lbCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 60, 30));

        lbQtd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbQtd.setText("QTD:");
        lbQtd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pProdutos.add(lbQtd, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 35, 30));

        btEditar.setBackground(new java.awt.Color(204, 204, 204));
        btEditar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });
        pProdutos.add(btEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, 70, 30));

        btSalvar.setBackground(new java.awt.Color(0, 255, 0));
        btSalvar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        pProdutos.add(btSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 70, 30));

        btNovo.setBackground(new java.awt.Color(0, 102, 255));
        btNovo.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });
        pProdutos.add(btNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 70, 30));

        btBuscar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });
        pProdutos.add(btBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 70, 30));
        pProdutos.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 402, 630, 10));

        btCancelar.setBackground(new java.awt.Color(255, 56, 0));
        btCancelar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        pProdutos.add(btCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 80, 30));

        jTabbedPane1.addTab("Produtos", pProdutos);

        pClientes.setMaximumSize(new java.awt.Dimension(640, 520));
        pClientes.setMinimumSize(new java.awt.Dimension(640, 520));
        pClientes.setPreferredSize(new java.awt.Dimension(656, 558));
        pClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfbuscar1.setPreferredSize(new java.awt.Dimension(6, 21));
        pClientes.add(tfbuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 180, 30));

        btBuscar1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btBuscar1.setText("Buscar");
        btBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscar1ActionPerformed(evt);
            }
        });
        pClientes.add(btBuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 70, 30));

        btAnterior1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btAnterior1.setText("<<");
        btAnterior1.setToolTipText("Anterior");
        btAnterior1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnterior1ActionPerformed(evt);
            }
        });
        pClientes.add(btAnterior1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 50, 30));

        lbValorAtual1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbValorAtual1.setText("1");
        lbValorAtual1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pClientes.add(lbValorAtual1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 30, 30));

        btProximo1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btProximo1.setText(">>");
        btProximo1.setToolTipText("Próximo");
        btProximo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProximo1ActionPerformed(evt);
            }
        });
        pClientes.add(btProximo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 50, 30));

        tfCodigo1.setPreferredSize(new java.awt.Dimension(6, 21));
        pClientes.add(tfCodigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 150, 30));

        tfNome1.setPreferredSize(new java.awt.Dimension(6, 21));
        pClientes.add(tfNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 230, 30));

        tfDescricao1.setPreferredSize(new java.awt.Dimension(6, 21));
        pClientes.add(tfDescricao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 230, 30));

        tfMediaCompras.setPreferredSize(new java.awt.Dimension(6, 21));
        pClientes.add(tfMediaCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 230, 30));

        tfFrequencia.setPreferredSize(new java.awt.Dimension(6, 21));
        pClientes.add(tfFrequencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 230, 30));

        lbPrecoVenda1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPrecoVenda1.setText("E-mail:");
        pClientes.add(lbPrecoVenda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 90, 30));

        lbPrecoCompra1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPrecoCompra1.setText("Média Compra:");
        pClientes.add(lbPrecoCompra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 110, 30));

        lbDescricao1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDescricao1.setText("Endereço:");
        pClientes.add(lbDescricao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 60, 30));

        lbNome1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNome1.setText("Nome:");
        pClientes.add(lbNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 50, 30));

        lbCodigo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCodigo1.setText("Código:");
        pClientes.add(lbCodigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 60, 30));

        btNovo1.setBackground(new java.awt.Color(0, 102, 255));
        btNovo1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btNovo1.setText("Novo");
        btNovo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovo1ActionPerformed(evt);
            }
        });
        pClientes.add(btNovo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 70, 30));

        btSalvar1.setBackground(new java.awt.Color(0, 255, 0));
        btSalvar1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btSalvar1.setText("Salvar");
        btSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvar1ActionPerformed(evt);
            }
        });
        pClientes.add(btSalvar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 70, 30));

        btEditar1.setBackground(new java.awt.Color(204, 204, 204));
        btEditar1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btEditar1.setText("Editar");
        btEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditar1ActionPerformed(evt);
            }
        });
        pClientes.add(btEditar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, 70, 30));

        btExcluir1.setBackground(new java.awt.Color(255, 51, 51));
        btExcluir1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btExcluir1.setText("Excluir");
        btExcluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluir1ActionPerformed(evt);
            }
        });
        pClientes.add(btExcluir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, 70, 30));
        pClientes.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 402, 630, 10));

        tfCidade1.setPreferredSize(new java.awt.Dimension(6, 21));
        pClientes.add(tfCidade1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 230, 30));

        lbTamanho4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTamanho4.setText("Cidade:");
        pClientes.add(lbTamanho4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 60, 30));

        lbTamanho5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTamanho5.setText("UF:");
        pClientes.add(lbTamanho5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 60, 30));

        tfUf1.setPreferredSize(new java.awt.Dimension(6, 21));
        pClientes.add(tfUf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 130, 30));

        tfTelefone1.setPreferredSize(new java.awt.Dimension(6, 21));
        pClientes.add(tfTelefone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 230, 30));

        lbPrecoCompra3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPrecoCompra3.setText("Telefone:");
        pClientes.add(lbPrecoCompra3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 110, 30));

        lbQtd4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbQtd4.setText("QTD:");
        lbQtd4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pClientes.add(lbQtd4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 35, 30));

        lbValorQtd4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbValorQtd4.setText("1");
        lbValorQtd4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pClientes.add(lbValorQtd4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 60, 30));

        btCancelar3.setBackground(new java.awt.Color(255, 56, 0));
        btCancelar3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btCancelar3.setText("Cancelar");
        btCancelar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelar3ActionPerformed(evt);
            }
        });
        pClientes.add(btCancelar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 80, 30));

        jTabbedPane1.addTab("Clientes", pClientes);

        pFornecedores.setMaximumSize(new java.awt.Dimension(640, 520));
        pFornecedores.setMinimumSize(new java.awt.Dimension(640, 520));
        pFornecedores.setPreferredSize(new java.awt.Dimension(656, 558));
        pFornecedores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfbuscar2.setPreferredSize(new java.awt.Dimension(6, 21));
        pFornecedores.add(tfbuscar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 180, 30));

        btBuscar2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btBuscar2.setText("Buscar");
        btBuscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscar2ActionPerformed(evt);
            }
        });
        pFornecedores.add(btBuscar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 70, 30));

        btAnterior2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btAnterior2.setText("<<");
        btAnterior2.setToolTipText("Anterior");
        btAnterior2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnterior2ActionPerformed(evt);
            }
        });
        pFornecedores.add(btAnterior2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 50, 30));

        lbValorAtual2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbValorAtual2.setText("1");
        lbValorAtual2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pFornecedores.add(lbValorAtual2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 30, 30));

        btProximo2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btProximo2.setText(">>");
        btProximo2.setToolTipText("Próximo");
        btProximo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProximo2ActionPerformed(evt);
            }
        });
        pFornecedores.add(btProximo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 50, 30));

        tfCodigo2.setPreferredSize(new java.awt.Dimension(6, 21));
        pFornecedores.add(tfCodigo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 150, 30));

        tfNome2.setPreferredSize(new java.awt.Dimension(6, 21));
        pFornecedores.add(tfNome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 230, 30));

        tfDescricao2.setPreferredSize(new java.awt.Dimension(6, 21));
        pFornecedores.add(tfDescricao2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 230, 30));

        tfTelefone.setPreferredSize(new java.awt.Dimension(6, 21));
        pFornecedores.add(tfTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 230, 30));

        tfEmail.setPreferredSize(new java.awt.Dimension(6, 21));
        pFornecedores.add(tfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 230, 30));

        tfEndereco.setPreferredSize(new java.awt.Dimension(6, 21));
        pFornecedores.add(tfEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 230, 30));

        tfCidade.setPreferredSize(new java.awt.Dimension(6, 21));
        pFornecedores.add(tfCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 230, 30));

        lbTamanho2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTamanho2.setText("Cidade:");
        pFornecedores.add(lbTamanho2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 60, 30));

        lbFornecedor2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFornecedor2.setText("Endereço:");
        pFornecedores.add(lbFornecedor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 60, 30));

        lbPrecoVenda2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPrecoVenda2.setText("E-mail:");
        pFornecedores.add(lbPrecoVenda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 90, 30));

        lbPrecoCompra2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPrecoCompra2.setText("Telefone:");
        pFornecedores.add(lbPrecoCompra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 110, 30));

        lbDescricao2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDescricao2.setText("Descrição:");
        pFornecedores.add(lbDescricao2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 60, 30));

        lbNome2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNome2.setText("Nome:");
        pFornecedores.add(lbNome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 50, 30));

        lbCodigo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCodigo2.setText("Código:");
        pFornecedores.add(lbCodigo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 60, 30));

        btSalvar2.setBackground(new java.awt.Color(0, 255, 0));
        btSalvar2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btSalvar2.setText("Salvar");
        btSalvar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvar2ActionPerformed(evt);
            }
        });
        pFornecedores.add(btSalvar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 70, 30));

        btEditar2.setBackground(new java.awt.Color(204, 204, 204));
        btEditar2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btEditar2.setText("Editar");
        btEditar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditar2ActionPerformed(evt);
            }
        });
        pFornecedores.add(btEditar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, 70, 30));

        btExcluir2.setBackground(new java.awt.Color(255, 51, 51));
        btExcluir2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btExcluir2.setText("Excluir");
        btExcluir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluir2ActionPerformed(evt);
            }
        });
        pFornecedores.add(btExcluir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, 70, 30));
        pFornecedores.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 402, 630, 10));

        tfUf.setPreferredSize(new java.awt.Dimension(6, 21));
        pFornecedores.add(tfUf, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 130, 30));

        lbTamanho3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTamanho3.setText("UF:");
        pFornecedores.add(lbTamanho3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 60, 30));

        lbQtd3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbQtd3.setText("QTD:");
        lbQtd3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pFornecedores.add(lbQtd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 35, 30));

        lbValorQtd3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbValorQtd3.setText("1");
        lbValorQtd3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pFornecedores.add(lbValorQtd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 60, 30));

        btNovo3.setBackground(new java.awt.Color(0, 102, 255));
        btNovo3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btNovo3.setText("Novo");
        btNovo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovo3ActionPerformed(evt);
            }
        });
        pFornecedores.add(btNovo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 70, 30));

        btCancelar1.setBackground(new java.awt.Color(255, 56, 0));
        btCancelar1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btCancelar1.setText("Cancelar");
        btCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelar1ActionPerformed(evt);
            }
        });
        pFornecedores.add(btCancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 80, 30));

        jTabbedPane1.addTab("Fornecedores", pFornecedores);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 656, 558));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(672, 596));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        buscarProdutosByCriteria(tfbuscar.getText());
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscar1ActionPerformed
        buscarClientesByCriteria(tfbuscar1.getText());
    }//GEN-LAST:event_btBuscar1ActionPerformed

    private void btBuscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscar2ActionPerformed
        buscarFornecedoresByCriteria(tfbuscar2.getText());
    }//GEN-LAST:event_btBuscar2ActionPerformed

    private void btAnterior2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnterior2ActionPerformed
        lastFornecedor();
    }//GEN-LAST:event_btAnterior2ActionPerformed

    private void btProximo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProximo2ActionPerformed
        proxFornecedor();
    }//GEN-LAST:event_btProximo2ActionPerformed

    private void btAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnteriorActionPerformed
        lastProduto();
    }//GEN-LAST:event_btAnteriorActionPerformed

    private void btProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProximoActionPerformed
        proxProduto();
    }//GEN-LAST:event_btProximoActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        prodEditable();
        produtoAtual = produtos.size();
        prepareComponents();
        tfCodigo.setText("");
        tfNome.setText("");
        tfDescricao.setText("");
        tfPrecoCompra.setText("");
        tfPrecoVenda.setText("");
        tfFornecedor.setText("");
        tfTamanho.setText("");
    }//GEN-LAST:event_btNovoActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        Produto prod = new Produto();
        prod.setCod(tfCodigo.getText());
        prod.setNome(tfNome.getText());
        prod.setDescricao(tfDescricao.getText());
        prod.setPrecoCompra(tfPrecoCompra.getText());
        prod.setPrecoVenda(tfPrecoVenda.getText());
        prod.setFornecedor(tfFornecedor.getText());
        prod.setTamanho(tfTamanho.getText());
        if (produtoAtual >= produtos.size()) {
            produtos.add(prod);
            System.out.println("\nproduto"+prod.toString());
            prControl.novoProduto(prod);
        } else {
            produtos.set(produtoAtual, prod);
            prControl.setProdutos(produtos);
        }
        prepareComponents();
        prodNotEditable();
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btProximo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProximo1ActionPerformed
        proxCliente();
    }//GEN-LAST:event_btProximo1ActionPerformed

    private void btAnterior1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnterior1ActionPerformed
        lastCliente();
    }//GEN-LAST:event_btAnterior1ActionPerformed

    private void btSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvar1ActionPerformed
        Cliente prod = new Cliente();
        prod.setCod(tfCodigo1.getText());
        prod.setNome(tfNome1.getText());
        prod.setMediaCompra(tfMediaCompras.getText());
        prod.setTelefone(tfTelefone1.getText());
        prod.setEmail(tfFrequencia.getText());
        prod.setEndereco(tfDescricao1.getText());
        prod.setCidade(tfCidade1.getText());
        prod.setUf(tfUf1.getText());
        if (produtoAtual >= produtos.size()) {
            clientes.add(prod);
            clControl.salvarNovoCliente(prod);
        } else {
            clientes.set(produtoAtual, prod);
            clControl.setClientes(clientes);
        }
        prepareComponents();
        cliNotEditable();
    }//GEN-LAST:event_btSalvar1ActionPerformed

    private void btSalvar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvar2ActionPerformed
        Fornecedor prod = new Fornecedor();
        prod.setCod(tfCodigo2.getText());
        prod.setNome(tfNome2.getText());
        prod.setDescricao(tfDescricao2.getText());
        prod.setTelefone(tfTelefone.getText());
        prod.setEmail(tfEmail.getText());
        prod.setEndereco(tfEndereco.getText());
        prod.setCidade(tfCidade.getText());
        prod.setUf(tfUf.getText());
        if ( fornecedorAtual >= fornecedores.size() ) {
            fornecedores.add(prod);
            frControl.novoFornecedor(prod);
        } else {
            fornecedores.set(fornecedorAtual, prod);
            frControl.setFornecedores(fornecedores);
        }
        prepareComponents();
        forNotEditable();
    }//GEN-LAST:event_btSalvar2ActionPerformed

    private void btNovo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovo1ActionPerformed
        cliEditable();
        clienteAtual = clientes.size();
        prepareComponents();
        tfCodigo1.setText("");
        tfNome1.setText("");
        tfMediaCompras.setText("");
        tfTelefone1.setText("");
        tfFrequencia.setText("");
        tfDescricao1.setText("");
        tfCidade1.setText("");
        tfUf1.setText("");

    }//GEN-LAST:event_btNovo1ActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        prodEditable();
    }//GEN-LAST:event_btEditarActionPerformed

    private void btEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditar1ActionPerformed
        cliEditable();
    }//GEN-LAST:event_btEditar1ActionPerformed

    private void btEditar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditar2ActionPerformed
        forEditable();
    }//GEN-LAST:event_btEditar2ActionPerformed

    private void btNovo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovo3ActionPerformed
        forEditable();
        fornecedorAtual = fornecedores.size();
        prepareComponents();
        tfCodigo2.setText("");
        tfNome2.setText("");
        tfDescricao2.setText("");
        tfTelefone.setText("");
        tfEmail.setText("");
        tfEndereco.setText("");
        tfCidade.setText("");
        tfUf.setText("");
    }//GEN-LAST:event_btNovo3ActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        prodNotEditable();
        produtoAtual--;
        proxProduto();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btCancelar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelar3ActionPerformed
        cliNotEditable();
        clienteAtual--;
        proxCliente();
    }//GEN-LAST:event_btCancelar3ActionPerformed

    private void btCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelar1ActionPerformed
        forNotEditable();
        fornecedorAtual--;
        proxFornecedor();
    }//GEN-LAST:event_btCancelar1ActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        produtos.remove(produtoAtual);
        prepareComponents();
        proxProduto();
        prControl.setProdutos(produtos);
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btExcluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluir1ActionPerformed
        clientes.remove(clienteAtual);
        prepareComponents();
        proxCliente();
        clControl.setClientes(clientes);
    }//GEN-LAST:event_btExcluir1ActionPerformed

    private void btExcluir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluir2ActionPerformed
        fornecedores.remove(fornecedorAtual);
        prepareComponents();
        proxFornecedor();
        frControl.setFornecedores(fornecedores);
    }//GEN-LAST:event_btExcluir2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePDM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePDM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePDM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePDM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePDM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnterior;
    private javax.swing.JButton btAnterior1;
    private javax.swing.JButton btAnterior2;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btBuscar1;
    private javax.swing.JButton btBuscar2;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btCancelar1;
    private javax.swing.JButton btCancelar3;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btEditar1;
    private javax.swing.JButton btEditar2;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btExcluir1;
    private javax.swing.JButton btExcluir2;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btNovo1;
    private javax.swing.JButton btNovo3;
    private javax.swing.JButton btProximo;
    private javax.swing.JButton btProximo1;
    private javax.swing.JButton btProximo2;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btSalvar1;
    private javax.swing.JButton btSalvar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbCodigo1;
    private javax.swing.JLabel lbCodigo2;
    private javax.swing.JLabel lbDescricao;
    private javax.swing.JLabel lbDescricao1;
    private javax.swing.JLabel lbDescricao2;
    private javax.swing.JLabel lbFornecedor;
    private javax.swing.JLabel lbFornecedor2;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbNome1;
    private javax.swing.JLabel lbNome2;
    private javax.swing.JLabel lbPrecoCompra;
    private javax.swing.JLabel lbPrecoCompra1;
    private javax.swing.JLabel lbPrecoCompra2;
    private javax.swing.JLabel lbPrecoCompra3;
    private javax.swing.JLabel lbPrecoVenda;
    private javax.swing.JLabel lbPrecoVenda1;
    private javax.swing.JLabel lbPrecoVenda2;
    private javax.swing.JLabel lbQtd;
    private javax.swing.JLabel lbQtd3;
    private javax.swing.JLabel lbQtd4;
    private javax.swing.JLabel lbTamanho;
    private javax.swing.JLabel lbTamanho2;
    private javax.swing.JLabel lbTamanho3;
    private javax.swing.JLabel lbTamanho4;
    private javax.swing.JLabel lbTamanho5;
    private javax.swing.JLabel lbValorAtual;
    private javax.swing.JLabel lbValorAtual1;
    private javax.swing.JLabel lbValorAtual2;
    private javax.swing.JLabel lbValorQtd;
    private javax.swing.JLabel lbValorQtd3;
    private javax.swing.JLabel lbValorQtd4;
    private javax.swing.JPanel pClientes;
    private javax.swing.JPanel pFornecedores;
    private javax.swing.JPanel pInicio;
    private javax.swing.JPanel pProdutos;
    private javax.swing.JTextField tfCidade;
    private javax.swing.JTextField tfCidade1;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfCodigo1;
    private javax.swing.JTextField tfCodigo2;
    private javax.swing.JTextField tfDescricao;
    private javax.swing.JTextField tfDescricao1;
    private javax.swing.JTextField tfDescricao2;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfEndereco;
    private javax.swing.JTextField tfFornecedor;
    private javax.swing.JTextField tfFrequencia;
    private javax.swing.JTextField tfMediaCompras;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfNome1;
    private javax.swing.JTextField tfNome2;
    private javax.swing.JTextField tfPrecoCompra;
    private javax.swing.JTextField tfPrecoVenda;
    private javax.swing.JTextField tfTamanho;
    private javax.swing.JTextField tfTelefone;
    private javax.swing.JTextField tfTelefone1;
    private javax.swing.JTextField tfUf;
    private javax.swing.JTextField tfUf1;
    private javax.swing.JTextField tfbuscar;
    private javax.swing.JTextField tfbuscar1;
    private javax.swing.JTextField tfbuscar2;
    // End of variables declaration//GEN-END:variables

    private void prepareComponents() {
        lbValorQtd.setText(String.valueOf((produtos == null)? 0 : produtos.size()));
        lbValorQtd4.setText(String.valueOf((clientes == null)? 0 : clientes.size()));
        lbValorQtd3.setText(String.valueOf((fornecedores == null)? 0 : fornecedores.size()));
        lbValorAtual.setText(String.valueOf((produtoAtual < 0 )? "-" : produtoAtual+1));
        lbValorAtual1.setText(String.valueOf((clienteAtual < 0 )? "-" : clienteAtual+1));
        lbValorAtual2.setText(String.valueOf((fornecedorAtual < 0 )? "-" : fornecedorAtual+1));
    }
    
    private void prodNotEditable() {
        tfCodigo.setEditable(false);
        tfNome.setEditable(false);
        tfDescricao.setEditable(false);
        tfPrecoCompra.setEditable(false);
        tfPrecoVenda.setEditable(false);
        tfFornecedor.setEditable(false);
        tfTamanho.setEditable(false);
        
        btSalvar.setEnabled(false);
        btNovo.setEnabled(true);
        btEditar.setEnabled(true);
        btExcluir.setEnabled(true);
        btBuscar.setEnabled(true);
        btCancelar.setEnabled(false);
        btAnterior.setEnabled(true);
        btProximo.setEnabled(true);
    }
    
    private void cliNotEditable() {
        tfCodigo1.setEditable(false);
        tfNome1.setEditable(false);
        tfMediaCompras.setEditable(false);
        tfTelefone1.setEditable(false);
        tfFrequencia.setEditable(false);
        tfDescricao1.setEditable(false);
        tfCidade1.setEditable(false);
        tfUf1.setEditable(false);
        
        btSalvar1.setEnabled(false);
        btNovo1.setEnabled(true);        
        btEditar1.setEnabled(true);
        btExcluir1.setEnabled(true);
        btBuscar1.setEnabled(true);
        btCancelar3.setEnabled(false);
        btAnterior1.setEnabled(true);
        btProximo1.setEnabled(true);
    }
    
    private void forNotEditable() {
        tfCodigo2.setEditable(false);
        tfNome2.setEditable(false);
        tfDescricao2.setEditable(false);
        tfTelefone.setEditable(false);
        tfEmail.setEditable(false);
        tfEndereco.setEditable(false);
        tfCidade.setEditable(false);
        tfUf.setEditable(false);
        
        btSalvar2.setEnabled(false);
        btNovo3.setEnabled(true);
        btEditar2.setEnabled(true);
        btExcluir2.setEnabled(true);
        btBuscar2.setEnabled(true);
        btCancelar1.setEnabled(false);
        btAnterior2.setEnabled(true);
        btProximo2.setEnabled(true);
    }

    
    
    

    private void prodEditable() {
        tfCodigo.setEditable(true);
        tfNome.setEditable(true);
        tfDescricao.setEditable(true);
        tfPrecoCompra.setEditable(true);
        tfPrecoVenda.setEditable(true);
        tfFornecedor.setEditable(true);
        tfTamanho.setEditable(true);
        
        btSalvar.setEnabled(true);
        btNovo.setEnabled(false);
        btEditar.setEnabled(false);
        btExcluir.setEnabled(false);
        btBuscar.setEnabled(false);
        btCancelar.setEnabled(true);
        btAnterior.setEnabled(false);
        btProximo.setEnabled(false);
    }
    
    private void cliEditable() {
        tfCodigo1.setEditable(true);
        tfNome1.setEditable(true);
        tfMediaCompras.setEditable(true);
        tfTelefone1.setEditable(true);
        tfFrequencia.setEditable(true);
        tfDescricao1.setEditable(true);
        tfCidade1.setEditable(true);
        tfUf1.setEditable(true);
        
        btSalvar1.setEnabled(true);
        btNovo1.setEnabled(false);
        btEditar1.setEnabled(false);
        btExcluir1.setEnabled(false);
        btBuscar1.setEnabled(false);
        btCancelar3.setEnabled(true);
        btAnterior1.setEnabled(false);
        btProximo1.setEnabled(false);
    }
    
    private void forEditable() {
        tfCodigo2.setEditable(true);
        tfNome2.setEditable(true);
        tfDescricao2.setEditable(true);
        tfTelefone.setEditable(true);
        tfEmail.setEditable(true);
        tfEndereco.setEditable(true);
        tfCidade.setEditable(true);
        tfUf.setEditable(true);
        
        btSalvar2.setEnabled(true);
        btNovo3.setEnabled(false);
        btEditar2.setEnabled(false);
        btExcluir2.setEnabled(false);
        btBuscar2.setEnabled(false);
        btCancelar1.setEnabled(true);
        btAnterior2.setEnabled(false);
        btProximo2.setEnabled(false);
    }



    
    
    
    private void buscarProdutosByCriteria(String query) {
        produtos = prControl.getAllProdutos();
        System.out.println("size produtos" + produtos.size());
        lbValorQtd.setText(String.valueOf(produtos.size()));
        proxProduto();
        prepareComponents();
    }
    
    private void buscarClientesByCriteria(String query) {
        clientes = clControl.getAllClientes();
        lbValorQtd4.setText(String.valueOf(clientes.size()));
        proxCliente();
        prepareComponents();
    }
    
    private void buscarFornecedoresByCriteria(String query) {
        fornecedores = frControl.getAllFornecedores();
        lbValorQtd4.setText(String.valueOf(fornecedores.size()));
        proxFornecedor();
        prepareComponents();
    }

    private void proxProduto() {
        Produto prod;
        if(produtoAtual < 0) {
            prod = (produtos.size() > 0) ? produtos.get(0) : null;
            if(prod == null) {
                return;
            }
        } else if((produtoAtual+1) >= produtos.size()) {
            prod = null;
            return;
        }
        produtoAtual++;
        prod = produtos.get(produtoAtual);
        escreverProduto(prod);
    }
    
    private void escreverProduto(Produto prod) {
        tfCodigo.setText(prod.getCod());
        tfNome.setText(prod.getNome());
        tfDescricao.setText(prod.getDescricao());
        tfPrecoCompra.setText(prod.getPrecoCompra());
        tfPrecoVenda.setText(prod.getPrecoVenda());
        tfFornecedor.setText(prod.getFornecedor());
        tfTamanho.setText(prod.getTamanho());
        lbValorAtual.setText(String.valueOf((produtoAtual < 0 )? "-" : produtoAtual+1));
    }
    
    private void lastProduto() {
        Produto prod;
        if(produtoAtual < 0) {
            prod = (produtos.size() > 0) ? produtos.get(0) : null;
            if(prod == null) {
                lbValorQtd.setText("0");
                return;
            }
        } else if((produtoAtual-1) < 0) {
            prod = null;
            return;
        }
        produtoAtual--;
        prod = produtos.get(produtoAtual);
        escreverProduto(prod);
    }

    
    
    
    

    private void proxCliente() {
        Cliente prod;
        if(clienteAtual < 0) {
            prod = (clientes.size() > 0) ? clientes.get(0) : null;
            if(prod == null) {
//                lbValorQtd4.setText("0");
                return;
            }
        } else if((clienteAtual+1) >= clientes.size()) {
            prod = null;
            return;
        }
        clienteAtual++;
        prod = clientes.get(clienteAtual);
        escreverCliente(prod);
    }
    
    private void escreverCliente(Cliente prod) {
        tfCodigo1.setText(prod.getCod());
        tfNome1.setText(prod.getNome());
        tfMediaCompras.setText(prod.getMediaCompra());
        tfTelefone1.setText(prod.getTelefone());
        tfFrequencia.setText(prod.getEmail());
        tfDescricao1.setText(prod.getEndereco());
        tfCidade1.setText(prod.getCidade());
        tfUf1.setText(prod.getUf());
        lbValorAtual1.setText(String.valueOf((clienteAtual < 0 )? "-" : clienteAtual+1));
    }
    
    private void lastCliente() {
        Cliente prod;
        if(clienteAtual < 0) {
            prod = (clientes.size() > 0) ? clientes.get(0) : null;
            if(prod == null) {
                lbValorQtd4.setText("0");
                return;
            }
        } else if((clienteAtual-1) < 0) {
            prod = null;
            return;
        }
        clienteAtual--;
        prod = clientes.get(clienteAtual);
        escreverCliente(prod);
    }

    
    
    
    
    
    
    public void proxFornecedor() {
        Fornecedor fr;
        if(fornecedorAtual < 0) {
            fr = (fornecedores.size() > 0) ? fornecedores.get(0) : null;
            if(fr == null) {
//                lbValorQtd3.setText("0");
                return;
            }
        } else if((fornecedorAtual+1) >= fornecedores.size()) {
            fr = null;
            return;
        }
        fornecedorAtual++;
        fr = fornecedores.get(fornecedorAtual);
        escreverFornecedor(fr);
    }

    
    private void escreverFornecedor(Fornecedor fr) {
        tfCodigo2.setText(fr.getCod());
        tfNome2.setText(fr.getNome());
        tfDescricao2.setText(fr.getDescricao());
        tfTelefone.setText(fr.getTelefone());
        tfEmail.setText(fr.getEmail());
        tfEndereco.setText(fr.getEndereco());
        tfCidade.setText(fr.getCidade());
        tfUf.setText(fr.getUf());
        lbValorAtual2.setText(String.valueOf((fornecedorAtual < 0 )? "-" : fornecedorAtual+1));
    }
    
    private void lastFornecedor() {
        Fornecedor fr;
        if(fornecedorAtual < 0) {
            fr = (fornecedores.size() > 0) ? fornecedores.get(0) : null;
            if(fr == null) {
                lbValorQtd3.setText("0");
                return;
            }
        } else if((fornecedorAtual-1) < 0) {
            fr = null;
            return;
        }
        fornecedorAtual--;
        fr = fornecedores.get(fornecedorAtual);
        escreverFornecedor(fr);
    }
    
    
}
