/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pdm.view;

/**
 *
 * @author Uso Exclusivo
 */
public class JFramePDM extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public JFramePDM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pInicio = new javax.swing.JPanel();
        pProdutos = new javax.swing.JPanel();
        tfFornecedor = new javax.swing.JTextField();
        btAnterior = new javax.swing.JButton();
        btProximo = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        lbValorQtd = new javax.swing.JLabel();
        lbTamanho = new javax.swing.JLabel();
        lbValorAtual = new javax.swing.JLabel();
        tfPrecoVenda = new javax.swing.JTextField();
        tfPrecoCompra = new javax.swing.JTextField();
        tfDescricao = new javax.swing.JTextField();
        tfNome = new javax.swing.JTextField();
        tfCodigo = new javax.swing.JTextField();
        tfTamanho = new javax.swing.JTextField();
        tfbuscar = new javax.swing.JTextField();
        lbFornecedor = new javax.swing.JLabel();
        lbPrecoVenda = new javax.swing.JLabel();
        lbPrecoCompra = new javax.swing.JLabel();
        lbDescricao = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        lbCodigo = new javax.swing.JLabel();
        lbQtd = new javax.swing.JLabel();
        btEditar = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();
        btBuscar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        pClientes = new javax.swing.JPanel();
        tfbuscar1 = new javax.swing.JTextField();
        btBuscar1 = new javax.swing.JButton();
        btAnterior1 = new javax.swing.JButton();
        lbValorAtual1 = new javax.swing.JLabel();
        btProximo1 = new javax.swing.JButton();
        tfCodigo1 = new javax.swing.JTextField();
        tfNome1 = new javax.swing.JTextField();
        tfDescricao1 = new javax.swing.JTextField();
        tfMediaCompras = new javax.swing.JTextField();
        tfFrequencia = new javax.swing.JTextField();
        lbPrecoVenda1 = new javax.swing.JLabel();
        lbPrecoCompra1 = new javax.swing.JLabel();
        lbDescricao1 = new javax.swing.JLabel();
        lbNome1 = new javax.swing.JLabel();
        lbCodigo1 = new javax.swing.JLabel();
        btNovo1 = new javax.swing.JButton();
        btSalvar1 = new javax.swing.JButton();
        btEditar1 = new javax.swing.JButton();
        btExcluir1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        tfCidade1 = new javax.swing.JTextField();
        lbTamanho4 = new javax.swing.JLabel();
        lbTamanho5 = new javax.swing.JLabel();
        tfUf1 = new javax.swing.JTextField();
        tfTelefone1 = new javax.swing.JTextField();
        lbPrecoCompra3 = new javax.swing.JLabel();
        lbQtd4 = new javax.swing.JLabel();
        lbValorQtd4 = new javax.swing.JLabel();
        pFornecedores = new javax.swing.JPanel();
        tfbuscar2 = new javax.swing.JTextField();
        btBuscar2 = new javax.swing.JButton();
        btAnterior2 = new javax.swing.JButton();
        lbValorAtual2 = new javax.swing.JLabel();
        btProximo2 = new javax.swing.JButton();
        tfCodigo2 = new javax.swing.JTextField();
        tfNome2 = new javax.swing.JTextField();
        tfDescricao2 = new javax.swing.JTextField();
        tfTelefone = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        tfEndereco = new javax.swing.JTextField();
        tfCidade = new javax.swing.JTextField();
        lbTamanho2 = new javax.swing.JLabel();
        lbFornecedor2 = new javax.swing.JLabel();
        lbPrecoVenda2 = new javax.swing.JLabel();
        lbPrecoCompra2 = new javax.swing.JLabel();
        lbDescricao2 = new javax.swing.JLabel();
        lbNome2 = new javax.swing.JLabel();
        lbCodigo2 = new javax.swing.JLabel();
        btNovo2 = new javax.swing.JButton();
        btSalvar2 = new javax.swing.JButton();
        btEditar2 = new javax.swing.JButton();
        btExcluir2 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        tfUf = new javax.swing.JTextField();
        lbTamanho3 = new javax.swing.JLabel();
        lbQtd3 = new javax.swing.JLabel();
        lbValorQtd3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PDM");
        setMinimumSize(new java.awt.Dimension(640, 520));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(656, 558));
        jPanel1.setMinimumSize(new java.awt.Dimension(640, 480));
        jPanel1.setName("panelFrame"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(656, 558));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setMaximumSize(new java.awt.Dimension(640, 480));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(640, 480));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(656, 558));

        pInicio.setMaximumSize(new java.awt.Dimension(640, 520));
        pInicio.setMinimumSize(new java.awt.Dimension(640, 520));
        pInicio.setPreferredSize(new java.awt.Dimension(656, 558));

        javax.swing.GroupLayout pInicioLayout = new javax.swing.GroupLayout(pInicio);
        pInicio.setLayout(pInicioLayout);
        pInicioLayout.setHorizontalGroup(
            pInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 651, Short.MAX_VALUE)
        );
        pInicioLayout.setVerticalGroup(
            pInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Inicio", pInicio);
        pInicio.getAccessibleContext().setAccessibleName("");

        pProdutos.setMaximumSize(new java.awt.Dimension(656, 558));
        pProdutos.setMinimumSize(new java.awt.Dimension(640, 520));
        pProdutos.setPreferredSize(new java.awt.Dimension(656, 558));
        pProdutos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfFornecedor.setPreferredSize(new java.awt.Dimension(6, 21));
        pProdutos.add(tfFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 230, 30));

        btAnterior.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btAnterior.setText("<<");
        btAnterior.setToolTipText("Anterior");
        pProdutos.add(btAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 50, 30));

        btProximo.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btProximo.setText(">>");
        btProximo.setToolTipText("Próximo");
        pProdutos.add(btProximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 50, 30));

        btExcluir.setBackground(new java.awt.Color(255, 51, 51));
        btExcluir.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btExcluir.setText("Excluir");
        pProdutos.add(btExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, 70, 30));

        lbValorQtd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbValorQtd.setText("1");
        lbValorQtd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pProdutos.add(lbValorQtd, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 60, 30));

        lbTamanho.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTamanho.setText("Tamanho:");
        pProdutos.add(lbTamanho, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 60, 30));

        lbValorAtual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbValorAtual.setText("1");
        lbValorAtual.setToolTipText("");
        lbValorAtual.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pProdutos.add(lbValorAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 30, 30));

        tfPrecoVenda.setPreferredSize(new java.awt.Dimension(6, 21));
        pProdutos.add(tfPrecoVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 230, 30));

        tfPrecoCompra.setPreferredSize(new java.awt.Dimension(6, 21));
        pProdutos.add(tfPrecoCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 230, 30));

        tfDescricao.setPreferredSize(new java.awt.Dimension(6, 21));
        pProdutos.add(tfDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 230, 30));

        tfNome.setPreferredSize(new java.awt.Dimension(6, 21));
        pProdutos.add(tfNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 230, 30));

        tfCodigo.setPreferredSize(new java.awt.Dimension(6, 21));
        pProdutos.add(tfCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 150, 30));

        tfTamanho.setPreferredSize(new java.awt.Dimension(6, 21));
        pProdutos.add(tfTamanho, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 230, 30));

        tfbuscar.setPreferredSize(new java.awt.Dimension(6, 21));
        pProdutos.add(tfbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 180, 30));

        lbFornecedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFornecedor.setText("Fornecedor:");
        pProdutos.add(lbFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 70, 30));

        lbPrecoVenda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPrecoVenda.setText("Preço Venda:");
        pProdutos.add(lbPrecoVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 90, 30));

        lbPrecoCompra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPrecoCompra.setText("Preço Compra:");
        pProdutos.add(lbPrecoCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 110, 30));

        lbDescricao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDescricao.setText("Descrição:");
        pProdutos.add(lbDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 60, 30));

        lbNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNome.setText("Nome:");
        pProdutos.add(lbNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 50, 30));

        lbCodigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCodigo.setText("Código:");
        pProdutos.add(lbCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 60, 30));

        lbQtd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbQtd.setText("QTD:");
        lbQtd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pProdutos.add(lbQtd, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 35, 30));

        btEditar.setBackground(new java.awt.Color(204, 204, 204));
        btEditar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btEditar.setText("Editar");
        pProdutos.add(btEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, 70, 30));

        btSalvar.setBackground(new java.awt.Color(0, 255, 0));
        btSalvar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btSalvar.setText("Salvar");
        pProdutos.add(btSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 70, 30));

        btNovo.setBackground(new java.awt.Color(0, 102, 255));
        btNovo.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btNovo.setText("Novo");
        pProdutos.add(btNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 70, 30));

        btBuscar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btBuscar.setText("Buscar");
        pProdutos.add(btBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 70, 30));
        pProdutos.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 402, 630, 10));

        jTabbedPane1.addTab("Produtos", pProdutos);

        pClientes.setMaximumSize(new java.awt.Dimension(640, 520));
        pClientes.setMinimumSize(new java.awt.Dimension(640, 520));
        pClientes.setPreferredSize(new java.awt.Dimension(656, 558));
        pClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfbuscar1.setPreferredSize(new java.awt.Dimension(6, 21));
        pClientes.add(tfbuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 180, 30));

        btBuscar1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btBuscar1.setText("Buscar");
        pClientes.add(btBuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 70, 30));

        btAnterior1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btAnterior1.setText("<<");
        btAnterior1.setToolTipText("Anterior");
        pClientes.add(btAnterior1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 50, 30));

        lbValorAtual1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbValorAtual1.setText("1");
        lbValorAtual1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pClientes.add(lbValorAtual1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 30, 30));

        btProximo1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btProximo1.setText(">>");
        btProximo1.setToolTipText("Próximo");
        pClientes.add(btProximo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 50, 30));

        tfCodigo1.setPreferredSize(new java.awt.Dimension(6, 21));
        pClientes.add(tfCodigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 150, 30));

        tfNome1.setPreferredSize(new java.awt.Dimension(6, 21));
        pClientes.add(tfNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 230, 30));

        tfDescricao1.setPreferredSize(new java.awt.Dimension(6, 21));
        pClientes.add(tfDescricao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 230, 30));

        tfMediaCompras.setPreferredSize(new java.awt.Dimension(6, 21));
        pClientes.add(tfMediaCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 230, 30));

        tfFrequencia.setPreferredSize(new java.awt.Dimension(6, 21));
        pClientes.add(tfFrequencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 230, 30));

        lbPrecoVenda1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPrecoVenda1.setText("E-mail:");
        pClientes.add(lbPrecoVenda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 90, 30));

        lbPrecoCompra1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPrecoCompra1.setText("Média Compra:");
        pClientes.add(lbPrecoCompra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 110, 30));

        lbDescricao1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDescricao1.setText("Endereço:");
        pClientes.add(lbDescricao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 60, 30));

        lbNome1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNome1.setText("Nome:");
        pClientes.add(lbNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 50, 30));

        lbCodigo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCodigo1.setText("Código:");
        pClientes.add(lbCodigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 60, 30));

        btNovo1.setBackground(new java.awt.Color(0, 102, 255));
        btNovo1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btNovo1.setText("Novo");
        pClientes.add(btNovo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 70, 30));

        btSalvar1.setBackground(new java.awt.Color(0, 255, 0));
        btSalvar1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btSalvar1.setText("Salvar");
        pClientes.add(btSalvar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 70, 30));

        btEditar1.setBackground(new java.awt.Color(204, 204, 204));
        btEditar1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btEditar1.setText("Editar");
        pClientes.add(btEditar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, 70, 30));

        btExcluir1.setBackground(new java.awt.Color(255, 51, 51));
        btExcluir1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btExcluir1.setText("Excluir");
        pClientes.add(btExcluir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, 70, 30));
        pClientes.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 402, 630, 10));

        tfCidade1.setPreferredSize(new java.awt.Dimension(6, 21));
        pClientes.add(tfCidade1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 230, 30));

        lbTamanho4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTamanho4.setText("Cidade:");
        pClientes.add(lbTamanho4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 60, 30));

        lbTamanho5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTamanho5.setText("UF:");
        pClientes.add(lbTamanho5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 60, 30));

        tfUf1.setPreferredSize(new java.awt.Dimension(6, 21));
        pClientes.add(tfUf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 130, 30));

        tfTelefone1.setPreferredSize(new java.awt.Dimension(6, 21));
        pClientes.add(tfTelefone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 230, 30));

        lbPrecoCompra3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPrecoCompra3.setText("Telefone:");
        pClientes.add(lbPrecoCompra3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 110, 30));

        lbQtd4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbQtd4.setText("QTD:");
        lbQtd4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pClientes.add(lbQtd4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 35, 30));

        lbValorQtd4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbValorQtd4.setText("1");
        lbValorQtd4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pClientes.add(lbValorQtd4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 60, 30));

        jTabbedPane1.addTab("Clientes", pClientes);

        pFornecedores.setMaximumSize(new java.awt.Dimension(640, 520));
        pFornecedores.setMinimumSize(new java.awt.Dimension(640, 520));
        pFornecedores.setPreferredSize(new java.awt.Dimension(656, 558));
        pFornecedores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfbuscar2.setPreferredSize(new java.awt.Dimension(6, 21));
        pFornecedores.add(tfbuscar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 180, 30));

        btBuscar2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btBuscar2.setText("Buscar");
        pFornecedores.add(btBuscar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 70, 30));

        btAnterior2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btAnterior2.setText("<<");
        btAnterior2.setToolTipText("Anterior");
        pFornecedores.add(btAnterior2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 50, 30));

        lbValorAtual2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbValorAtual2.setText("1");
        lbValorAtual2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pFornecedores.add(lbValorAtual2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 30, 30));

        btProximo2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btProximo2.setText(">>");
        btProximo2.setToolTipText("Próximo");
        pFornecedores.add(btProximo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 50, 30));

        tfCodigo2.setPreferredSize(new java.awt.Dimension(6, 21));
        pFornecedores.add(tfCodigo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 150, 30));

        tfNome2.setPreferredSize(new java.awt.Dimension(6, 21));
        pFornecedores.add(tfNome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 230, 30));

        tfDescricao2.setPreferredSize(new java.awt.Dimension(6, 21));
        pFornecedores.add(tfDescricao2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 230, 30));

        tfTelefone.setPreferredSize(new java.awt.Dimension(6, 21));
        pFornecedores.add(tfTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 230, 30));

        tfEmail.setPreferredSize(new java.awt.Dimension(6, 21));
        pFornecedores.add(tfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 230, 30));

        tfEndereco.setPreferredSize(new java.awt.Dimension(6, 21));
        pFornecedores.add(tfEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 230, 30));

        tfCidade.setPreferredSize(new java.awt.Dimension(6, 21));
        pFornecedores.add(tfCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 230, 30));

        lbTamanho2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTamanho2.setText("Cidade:");
        pFornecedores.add(lbTamanho2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 60, 30));

        lbFornecedor2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFornecedor2.setText("Endereço:");
        pFornecedores.add(lbFornecedor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 60, 30));

        lbPrecoVenda2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPrecoVenda2.setText("E-mail:");
        pFornecedores.add(lbPrecoVenda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 90, 30));

        lbPrecoCompra2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPrecoCompra2.setText("Telefone:");
        pFornecedores.add(lbPrecoCompra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 110, 30));

        lbDescricao2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDescricao2.setText("Descrição:");
        pFornecedores.add(lbDescricao2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 60, 30));

        lbNome2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNome2.setText("Nome:");
        pFornecedores.add(lbNome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 50, 30));

        lbCodigo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCodigo2.setText("Código:");
        pFornecedores.add(lbCodigo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 60, 30));

        btNovo2.setBackground(new java.awt.Color(0, 102, 255));
        btNovo2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btNovo2.setText("Novo");
        pFornecedores.add(btNovo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 70, 30));

        btSalvar2.setBackground(new java.awt.Color(0, 255, 0));
        btSalvar2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btSalvar2.setText("Salvar");
        pFornecedores.add(btSalvar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 70, 30));

        btEditar2.setBackground(new java.awt.Color(204, 204, 204));
        btEditar2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btEditar2.setText("Editar");
        pFornecedores.add(btEditar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, 70, 30));

        btExcluir2.setBackground(new java.awt.Color(255, 51, 51));
        btExcluir2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btExcluir2.setText("Excluir");
        pFornecedores.add(btExcluir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, 70, 30));
        pFornecedores.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 402, 630, 10));

        tfUf.setPreferredSize(new java.awt.Dimension(6, 21));
        pFornecedores.add(tfUf, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 130, 30));

        lbTamanho3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTamanho3.setText("UF:");
        pFornecedores.add(lbTamanho3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 60, 30));

        lbQtd3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbQtd3.setText("QTD:");
        lbQtd3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pFornecedores.add(lbQtd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 35, 30));

        lbValorQtd3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbValorQtd3.setText("1");
        lbValorQtd3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pFornecedores.add(lbValorQtd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 60, 30));

        jTabbedPane1.addTab("Fornecedores", pFornecedores);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 656, 558));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(672, 596));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePDM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePDM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePDM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePDM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePDM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnterior;
    private javax.swing.JButton btAnterior1;
    private javax.swing.JButton btAnterior2;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btBuscar1;
    private javax.swing.JButton btBuscar2;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btEditar1;
    private javax.swing.JButton btEditar2;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btExcluir1;
    private javax.swing.JButton btExcluir2;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btNovo1;
    private javax.swing.JButton btNovo2;
    private javax.swing.JButton btProximo;
    private javax.swing.JButton btProximo1;
    private javax.swing.JButton btProximo2;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btSalvar1;
    private javax.swing.JButton btSalvar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbCodigo1;
    private javax.swing.JLabel lbCodigo2;
    private javax.swing.JLabel lbDescricao;
    private javax.swing.JLabel lbDescricao1;
    private javax.swing.JLabel lbDescricao2;
    private javax.swing.JLabel lbFornecedor;
    private javax.swing.JLabel lbFornecedor2;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbNome1;
    private javax.swing.JLabel lbNome2;
    private javax.swing.JLabel lbPrecoCompra;
    private javax.swing.JLabel lbPrecoCompra1;
    private javax.swing.JLabel lbPrecoCompra2;
    private javax.swing.JLabel lbPrecoCompra3;
    private javax.swing.JLabel lbPrecoVenda;
    private javax.swing.JLabel lbPrecoVenda1;
    private javax.swing.JLabel lbPrecoVenda2;
    private javax.swing.JLabel lbQtd;
    private javax.swing.JLabel lbQtd3;
    private javax.swing.JLabel lbQtd4;
    private javax.swing.JLabel lbTamanho;
    private javax.swing.JLabel lbTamanho2;
    private javax.swing.JLabel lbTamanho3;
    private javax.swing.JLabel lbTamanho4;
    private javax.swing.JLabel lbTamanho5;
    private javax.swing.JLabel lbValorAtual;
    private javax.swing.JLabel lbValorAtual1;
    private javax.swing.JLabel lbValorAtual2;
    private javax.swing.JLabel lbValorQtd;
    private javax.swing.JLabel lbValorQtd3;
    private javax.swing.JLabel lbValorQtd4;
    private javax.swing.JPanel pClientes;
    private javax.swing.JPanel pFornecedores;
    private javax.swing.JPanel pInicio;
    private javax.swing.JPanel pProdutos;
    private javax.swing.JTextField tfCidade;
    private javax.swing.JTextField tfCidade1;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfCodigo1;
    private javax.swing.JTextField tfCodigo2;
    private javax.swing.JTextField tfDescricao;
    private javax.swing.JTextField tfDescricao1;
    private javax.swing.JTextField tfDescricao2;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfEndereco;
    private javax.swing.JTextField tfFornecedor;
    private javax.swing.JTextField tfFrequencia;
    private javax.swing.JTextField tfMediaCompras;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfNome1;
    private javax.swing.JTextField tfNome2;
    private javax.swing.JTextField tfPrecoCompra;
    private javax.swing.JTextField tfPrecoVenda;
    private javax.swing.JTextField tfTamanho;
    private javax.swing.JTextField tfTelefone;
    private javax.swing.JTextField tfTelefone1;
    private javax.swing.JTextField tfUf;
    private javax.swing.JTextField tfUf1;
    private javax.swing.JTextField tfbuscar;
    private javax.swing.JTextField tfbuscar1;
    private javax.swing.JTextField tfbuscar2;
    // End of variables declaration//GEN-END:variables
}
