-- MySQL Script generated by MySQL Workbench
-- Mon 29 May 2017 05:22:23 PM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pdm
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pdm` ;

-- -----------------------------------------------------
-- Schema pdm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pdm` DEFAULT CHARACTER SET utf8 ;
USE `pdm` ;

-- -----------------------------------------------------
-- Table `pdm`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pdm`.`cliente` ;

CREATE TABLE IF NOT EXISTS `pdm`.`cliente` (
  `cod` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NULL,
  `mediaCompra` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `uf` VARCHAR(45) NULL,
  PRIMARY KEY (`cod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pdm`.`fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pdm`.`fornecedor` ;

CREATE TABLE IF NOT EXISTS `pdm`.`fornecedor` (
  `cod` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NULL,
  `descricao` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `uf` VARCHAR(45) NULL,
  PRIMARY KEY (`cod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pdm`.`produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pdm`.`produto` ;

CREATE TABLE IF NOT EXISTS `pdm`.`produto` (
  `cod` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NULL,
  `descricao` VARCHAR(45) NULL,
  `precoCompra` VARCHAR(45) NULL,
  `precoVenda` VARCHAR(45) NULL,
  `tamanho` VARCHAR(45) NULL,
  `fornecedor` VARCHAR(45) NULL,
  PRIMARY KEY (`cod`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
